# Generated by Django 5.0.4 on 2024-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.TextField(blank='True', null='True', verbose_name='описание'),
            preserve_default='True',
        ),
    ]
