# Generated by Django 5.0.4 on 2024-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank="True", null="True", verbose_name="описание"),
        ),
    ]
