# Generated by Django 5.0.4 on 2024-05-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_created=True,
                blank="True",
                null="True",
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank="True", null="True", verbose_name="цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now_add=True, null="True", verbose_name="дата изменения"
            ),
        ),
    ]
